test('useSuccess throws error when not wrapped in SuccessProvider', () => {});

test('useSuccess does not throw error when wrapped in SuccessProvider', () => {});
